USE codeup_test_db;
TRUNCATE albums;

INSERT INTO albums (artist, name, release_date, genre, sales)
VALUES ( 'Michael Jackson','Thriller',1982,'Pop, Rock, R&B',66 ),
  ( 'AC/DC','Back in Black',1980,'Hard rock',50 ),
  ( 'Pink Floyd','The Dark Side of the Moon',1973,'Progressive rock',45 ),
  ( 'Meat Loaf','Bat Out of Hell',1977,'Hard rock, Progressive rock',43 ),
  ( 'Whitney Houston / Various artists','The Bodyguard',1992,'R&B, Soul, Pop, Soundtrack',42 ),
  ( 'Eagles','Their Greatest Hits (1971–1975)',1976,'Rock, Soft rock, Folk rock',42 ),
  ( 'Bee Gees / Various artists','Saturday Night Fever',1977,'Disco',40 ),
  ( 'Fleetwood Mac','Rumours',1977,'Soft rock',40 ),
  ( 'Various artists','Grease: The Original Soundtrack from the Motion Picture',1978,'Soundtrack',38 ),
  ( 'Led Zeppelin','Led Zeppelin IV',1971,'Hard rock, Heavy metal, Folk',37 ),
  ( 'Michael Jackson','Bad',1987,'Pop, Funk, Rock',35 ),
  ( 'Alanis Morissette','Jagged Little Pill',1995,'Alternative rock',33 ),
  ( 'Shania Twain','Come On Over',1997,'Country, Pop',33 ),
  ( 'Celine Dion','Falling into You',1996,'Pop, Soft rock',32 ),
  ( 'The Beatles','Sgt. Pepper''s Lonely Hearts Club Band',1967,'Rock',32 ),
  ( 'Eagles','Hotel California',1976,'Rock, Soft rock, Folk rock',32 ),
  ( 'Various artists','Dirty Dancing',1987,'Pop, Rock, R&B',32 ),
  ( 'Adele','21',2011,'Pop, Soul',31 ),
  ( 'Celine Dion','Let''s Talk About Love',1997,'Pop, Soft rock',31 ),
  ( 'The Beatles','1',2000,'Rock',31 ),
  ( 'Michael Jackson','Dangerous',1991,'Rock, Funk, Pop',30 ),
  ( 'Madonna','The Immaculate Collection',1990,'Pop, Dance',30 ),
  ( 'The Beatles','Abbey Road',1969,'Rock',30 ),
  ( 'Bruce Springsteen','Born in the U.S.A.',1984,'Rock',30 ),
  ( 'Dire Straits','Brothers in Arms',1985,'Rock, Pop',30 ),
  ( 'James Horner','Titanic: Music from the Motion Picture',1997,'Soundtrack',30 ),
  ( 'Metallica','Metallica',1991,'Thrash metal, Heavy metal',30 ),
  ( 'Nirvana','Nevermind',1991,'Grunge, Alternative rock',30 ),
  ( 'Pink Floyd','The Wall',1979,'Progressive rock',30 ),
  ( 'Santana','Supernatural',1999,'Rock',30 ),
  ( 'Guns N'' Roses','Appetite for Destruction',1987,'Hard rock',30 ),
  ( 'ABBA','Gold: Greatest Hits',1992,'Pop',28 ),
  ( 'Bon Jovi','Slippery When Wet',1986,'Hard rock, Glam metal',28 ),
  ( 'Mariah Carey','Music Box',1993,'Pop, R&B, Rock',28 ),
  ( 'Eminem','The Eminem Show',2002,'Hip Hop',27 ),
  ( 'Linkin Park','Hybrid Theory',2000,'Nu metal, Rap metal, Alternative metal',27 ),
  ( 'Norah Jones','Come Away with Me',2002,'Jazz',27 ),
  ( 'Eric Clapton','Unplugged',1992,'Acoustic rock, Acoustic blues',26 ),
  ( 'Madonna','True Blue',1986,'Pop',25 ),
  ( 'Bob Marley & The Wailers','Legend: The Best of Bob Marley & The Wailers',1984,'Reggae',25 ),
  ( 'Carole King','Tapestry',1971,'Pop',25 ),
  ( 'Phil Collins','No Jacket Required',1985,'Pop, Rock',25 ),
  ( 'Queen','Greatest Hits',1981,'Rock',25 ),
  ( 'Simon & Garfunkel','Bridge over Troubled Water',1970,'Folk rock',25 ),
  ( 'U2','The Joshua Tree',1987,'Rock',25 ),
  ( 'Britney Spears','...Baby One More Time',1999,'Pop',25 ),
  ( 'Backstreet Boys','Backstreet''s Back / Backstreet Boys',1997,'Pop',24 ),
  ( 'Backstreet Boys','Millennium',1999,'Pop',24 ),
  ( 'Spice Girls','Spice',1996,'Pop',23 ),
  ( 'Ace of Base','Happy Nation/The Sign',1993,'Pop',23 ),
  ( 'Whitney Houston','Whitney Houston',1985,'Pop, R&B',22 ),
  ( 'Oasis','(What''s the Story) Morning Glory?',1995,'Britpop, Rock',22 ),
  ( 'Eminem','The Marshall Mathers LP',2000,'Rap, hip-hop',21 ),
  ( 'Madonna','Like a Virgin',1984,'Pop, Dance',21 ),
  ( 'Bon Jovi','Cross Road',1994,'Hard rock, Glam metal',21 ),
  ( 'Adele','25',2015,'Soul, Pop, R&B',20 ),
  ( 'Boston','Boston',1976,'Hard rock',20 ),
  ( 'Britney Spears','Oops!... I Did It Again',2000,'Pop',20 ),
  ( 'Celine Dion','The Colour of My Love',1993,'Pop',20 ),
  ( 'Def Leppard','Hysteria',1987,'Pop, Hard rock',20 ),
  ( 'George Michael','Faith',1987,'Pop, R&B, Funk, Soul',20 ),
  ( 'Green Day','Dookie',1994,'Pop punk, Punk rock, Alternative rock',20 ),
  ( 'Lionel Richie','Can''t Slow Down',1983,'Pop, R&B, Soul',20 ),
  ( 'Mariah Carey','Daydream',1995,'Pop, R&B',20 ),
  ( 'Michael Jackson','HIStory: Past, Present and Future, Book I',1995,'Pop, Rock, R&B',20 ),
  ( 'Michael Jackson','Off the Wall',1979,'Soul, Disco, R&B',20 ),
  ( 'Shania Twain','The Woman in Me',1995,'Country, Pop',20 ),
  ( 'Supertramp','Breakfast in America',1979,'Progressive rock, Art rock',20 ),
  ( 'Tracy Chapman','Tracy Chapman',1988,'Folk rock',20 ),
  ( 'Various artists','Flashdance: Original Soundtrack from the Motion Picture',1983,'Soundtrack',20 ),
  ( 'Whitney Houston','Whitney',1987,'Pop, R&B',20 );

